#!/bin/sh
#
# do_header2 for Xclamation, XQuad, XAllWrite, XMayday, XInstall and 
# 	AxeneOffice in Utils/
# Make links to include file in Headers subdir
# Sh version: portable but slow
#
# Copyright (C) 1994-2000 Axene.
# Authors: Stéphane Boisson, Antoine Buat, Robin Castanier and Emmanuel Paris.
# Email: xcalibur@axene.org
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
# Started on  Tue Dec  9 17:33:19 1997 Emmanuel Paris
# Last update Mon Aug  7 18:20:09 2000 Emmanuel Paris
#

PWD=`pwd`
top=`dirname $PWD/$0`
header_dir=$top/../Headers
echonl="$top/echonl.sh"

[ -d $header_dir ] || mkdir -p $header_dir
[ -d $top/../lib ] || mkdir -p $top/../lib 

# ----------------------------------------------------------------- #
# LinkDir - Link all *.h in <path> and recursively call itsel in    #
#	    subdirectories.					    #
# ----------------------------------------------------------------- #
LinkDir()
{
 dir=$1 
 for file in $dir/*; do
  if [ -d $file ]; then 
   if [ `basename $file` != `basename $header_dir` ]; then
    LinkDir $dir/`basename $file`
    dir=$1
   fi
  else
   header=`echo $file | grep "\.h$"`
   if [ -n "$header" ]; then
    dst_file=`basename $header`
    if [ -r $dst_file ]; then 
     error=$error" "$dst_file
    else
     ln -s $header $dst_file
     count=`expr $count + 1`
     counth=`expr $counth + 1`
     if [ $count = 9 ]; then 
      $echonl "."
      count=0
     fi
    fi
   fi
  fi
 done
}

cd $header_dir

count=0
counth=0
$echonl "Cleaning Header files: "
for file in *; do
 if [ $file = "*" ]; then break; fi
 rm -f $file
 count=`expr $count + 1`
 counth=`expr $counth + 1`
 if [ $count = 9 ]; then 
  $echonl "."
  count=0
 fi
done
echo "done ($counth)."

clean=`echo $1 | grep "clea[rn]"`
if [ -n "$clean" ]; then
 exit 0
fi

count=0
counth=0
error=
$echonl "Linking Header files:  "
LinkDir ..
echo "done ($counth)."

if [ -n "$error" ]; then
 echo "$0 Error: The file(s):$error exist(s) in multiple times."
fi

touch uptodate

