#!/bin/sh

print_cmd=$1
printer=$2
device=$3
shift 3

echo $print_cmd $printer device=$device extra_flags $@ > /dev/console

cat | gs -q -g1240x1754 -r150x150 -dNOPAUSE -dNOPLATFONTS -sDEVICE=$device $@ -sOutputFile=/tmp/gs_file%d.tmp -

for _file in /tmp/gs_file*.tmp; do
  if [ -r $_file ]; then
    $print_cmd $printer $_file
    rm $_file
  fi
done










