#!/bin/tcsh -fb
#
# tarhNew for Xclamation, XQuad, XAllWrite, XMayday, XInstall and 
# 	AxeneOffice in Utils/
# Tar new file since arg1 day in arg2.tgz 
#
# Copyright (C) 1994-2000 Axene.
# Authors: Stéphane Boisson, Antoine Buat, Robin Castanier and Emmanuel Paris.
# Email: xcalibur@axene.org
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
# Started on  Tue Oct  4 11:11:32 1994 Stéphane Boisson
# Last update Sat Jun 12 17:47:21 1999 Emmanuel Paris
#

if ($# == 2) then
 set tms = `expr $argv[1] '*' 60`
 set t = `find . -mmin -$tms -print | fgrep -v ".o" | fgrep -v ".a" | fgrep -v "~" | fgrep -v ".zpm" | fgrep -v "core" | grep -v "Headers/"`
 set fi = ""
 foreach name ($t)
  if (! -d $name) then
   if (! -x $name) then
    set fi = `echo $fi $name`
   else
    set siz = ""
    set inc = 1
    while ($siz == "")
     set siz = `wc -c $name | cut -d" "  -f$inc`
     set inc = `expr $inc + 1`
    end
    if ( `expr $siz` < 10000 ) then
     set fi = `echo $fi $name`
    endif
   endif
  endif
 end
 gtar czvf $argv[2].tgz $fi
else
 echo "Usage tarhNew number(hour) file"
endif

