#!/bin/sh
#
# mkmakefile for Xclamation, XQuad, XAllWrite, XMayday, XInstall and 
# 	AxeneOffice in Utils/
# Script to automatically generate a working Makefile
# on various exotic OS (sco odt, unixware...)
#
# Copyright (C) 1994-2000 Axene.
# Authors: Stéphane Boisson, Antoine Buat, Robin Castanier and Emmanuel Paris.
# Email: xcalibur@axene.org
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
# Started on  Fri Feb 13 15:29:19 1998 Emmanuel Paris
# Last update Wed May 31 19:22:38 2000 Emmanuel Paris
#

osid=`cat << EOF
# hosttype     tag      os name	    makefile suffix
___generic	G	Generic		
___NetBSD	N	NetBSD		netbsd
___freebsd	F	FreeBSD		freebsd
___sco386	S	ScoODT		sco_odt
___sco386sV	V	ScoOpen/s5	sco_sv
___unixware	U	UnixWare	unixware
EOF`

interactive="no"
all="no"
PWD=`pwd`
top=`dirname $PWD/$0`
echonl="$top/echonl.sh"
srcmk="$top/../Makefile.in"
dstmk="$top/../Makefile"

# ----------------------------------------------------------------- # 
# extract from $osid the correct information.                       # 
# input:  hosttype in $1                                            # 
# output: hosttype in $hosttype                                     # 
#         tag in $ostag                                             # 
#         os name in $osname                                        # 
#         makefile suffix in $makefsuffix                           # 
# ----------------------------------------------------------------- #
get_os_info()
{
 _hosttype=$1

 _osline=`echo "$osid" | grep "^$_hosttype"`
 if [ "v$_osline" = "v" ]; then
  _osline=`echo "$osid" | grep "^___generic"`
 fi

 _i=0
 for _var in $_osline; do
  case $_i in
   0) hosttype=$_var;;
   1) ostag=$_var;;
   2) osname=$_var;;
   3) makefsuffix="."$_var;;
  esac 
  _i=`expr $_i + 1`
 done
}

# ----------------------------------------------------------------- # 
# Generate Main/Makefile                                            # 
# input:  tag in $1                                                 # 
#         suffix in $2 (optional)                                   # 
# ----------------------------------------------------------------- #
generate_makefile()
{
 OS=$1
 
 if [ $# = 2 ]; then
  _suffix=$2
 else
  _suffix=
 fi

 match1="^\\(^.*[^	]\\)	*#+.*[$OS].*$"
 match2="^\\(.*[^	]\\)	*#-[^$OS]*$"
 excld1="^.*#-.*[$OS].*$"
 excld2="^.*#+[^$OS]*$"

 cat $srcmk | grep -v "$excld1" | grep -v "$excld2" | sed -e "s/$match1/\1/" -e "s/$match2/\1/" -e "s/	*#[+-].*$//" > $dstmk$_suffix
}


if [ $# -gt 0 ]; then
 if [ $1 = "all" ]; then all="yes"; 
 elif [ $1 = "interactive" ]; then interactive="yes";
 fi
fi

if [ "$all" = "yes" ]; then
 echo "$osid" > __tmp
 exec 5<__tmp
 i=1
 while read osline <&5 ; do
  rgpr=`echo $osline | grep -e "^#.*"`
  if [ "v$rgpr" != "v" ]; then 
   continue
  fi
  get_os_info "$osline"
  echo -----------------------------------------------------------------------
  $echonl "Generate Makefile$makefsuffix for $hosttype ...."
  generate_makefile $ostag $makefsuffix
  echo done
 done
 echo -----------------------------------------------------------------------
 exec 5<&-
 rm -f __tmp 
else
 if [ "v$HOSTYPE" != "v" ]; then
  hosttype="___"$HOSTTYPE
 else
  if [ "v$CPPFLAGS" != "v" ]; then
   for hosttype in $CPPFLAGS; do
    rgrp=`echo $hosttype | grep ___ | sed -e "s/.*\\(___.*\\)/\1/"`
    if [ "v$rgrp" != "v" ]; then
     hosttype=$rgrp
     break
    fi
   done
  else
   interactive="yes"
  fi
 fi
 if [ "$interactive" = "yes" ]; then
  echo -----------------------------------------------------------------------
  echo "Select for witch os the Makefile must be create:"
  echo "$osid" > __tmp
  exec 5<__tmp
  i=1
  while read osline <&5 ; do
   rgpr=`echo $osline | grep -e "^#.*"`
   if [ "v$rgpr" != "v" ]; then 
    continue
   fi
   get_os_info "$osline"
   echo $i": ("$ostag")" $osname
   i=`expr $i + 1` 
  done
  exec 5<&-
  rm -f __tmp
  while :; do
   $echonl "Your selection: "
   read reply
   if [ "v$reply" = "v" ]; then continue; fi
   echo "$osid" > __tmp
   exec 5<__tmp
   i=1
   while read osline <&5 ; do
    rgpr=`echo $osline | grep -e "^#.*"`
    if [ "v$rgpr" != "v" ]; then 
     continue
    fi
    get_os_info "$osline"
    if [ "$reply" = "$i" -o "$reply" = "$ostag" ]; then
     i=0
     break
    fi
    i=`expr $i + 1` 
   done
   exec 5<&-
   rm -f __tmp
   if [ "$i" = "0" ]; then break; fi
  done
 fi
 get_os_info $hosttype
 echo -----------------------------------------------------------------------
 $echonl "Generate Makefile for $hosttype ...."
 generate_makefile $ostag
 echo done
fi

exit 0




