#!/bin/tcsh -fb
#
# do_link for Xclamation, XQuad, XAllWrite, XMayday, XInstall and 
# 	AxeneOffice in Utils/
# Make links to duplicate with links a project tree.
#
# Copyright (C) 1994-2000 Axene.
# Authors: Stéphane Boisson, Antoine Buat, Robin Castanier and Emmanuel Paris.
# Email: xcalibur@axene.org
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
# Started on  Mon Jun 13 15:10:29 1994 Stéphane Boisson
# Last update Fri Jan  7 14:31:48 2000 Emmanuel Paris
#
set PWD=`pwd`
set this="$PWD/$0"

if ($# == 1) then
 unalias ls
 set pwd1 = $argv[1]
 echo directory: ${pwd1}
 set list_file = `ls -1a $pwd1`
 foreach file (${list_file})
  if (-d ${pwd1}${file}) then
   set repertoire = $file
   if (${repertoire} != "..") then
   if (${repertoire} != ".") then
    if (! -d ${repertoire}) then
     echo creating directory ./${repertoire}
     mkdir ./${repertoire}
    endif
# recurse directory
    cd $repertoire
    $this ../${pwd1}${repertoire}/
    cd ..
   endif
   endif
  else
   if (! -e $file) then
    echo linking file ${pwd1}${file}
    ln -s ${pwd1}${file} .
   endif
  endif
 end
else
 echo "Usage do_link repstart"
endif
