#!/bin/sh
#
# do_ad for XInstall in Utils/
# Create all languages's AD files
#
# Copyright (C) 1997-2000 Axene.
# Authors: Stéphane Boisson, Antoine Buat, Robin Castanier and Emmanuel Paris.
# Email: xcalibur@axene.org
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
# Started on  Mon Dec  8 17:12:44 1997 Emmanuel Paris
# Last update Thu Aug 10 10:47:37 2000 Emmanuel Paris
#

PWD=`pwd`
top=`dirname $PWD/$0`
ad_dir="$top/../AD"
tongue_dir="$top/../Tongues"
global_dir="$top/../Global"
echonl="$top/echonl.sh"
ad2c="$top/ad2c.script"

$echonl "Making XInstall for tongues: English"
$ad2c $ad_dir/ADTongue.english > $tongue_dir/Tongue.english.h

$echonl ", French"
$ad2c $ad_dir/ADTongue.french > $tongue_dir/Tongue.french.h

$echonl ", German"
$ad2c $ad_dir/ADTongue.german > $tongue_dir/Tongue.german.h

echo " and Spanish."
$ad2c $ad_dir/ADTongue.spanish > $tongue_dir/Tongue.spanish.h

$echonl "Making XInstall.ad.h: "
cat $ad_dir/ADColor.gray > $global_dir/XInstall.ad
cat $ad_dir/ADParameters >> $global_dir/XInstall.ad
$ad2c $global_dir/XInstall.ad > $global_dir/XInstall.ad.h
rm -f $global_dir/XInstall.ad
echo "done."
