"*fontList:		-*-helvetica-medium-r-*-*-14-*-*-*-*-*-iso8859-1",
"*XmText.fontList:	-*-helvetica-medium-r-*-*-14-*-*-*-*-*-iso8859-1",
"*XmTextField.fontList:	-*-helvetica-medium-r-*-*-14-*-*-*-*-*-iso8859-1",
"*XmSrolledList.fontList:	-*-helvetica-medium-r-*-*-14-*-*-*-*-*-iso8859-1",
"*XmFrame.XmLabelGadget.fontList: -*-helvetica-medium-*-*-*-10-*-*-*-*-*-iso8859-1",
"*lFontSelect.fontList:	-*-helvetica-bold-o-*-*-14-*-*-*-*-*-iso8859-1",
"*FSTitle.fontList:	-*-helvetica-bold-o-*-*-14-*-*-*-*-*-iso8859-1",
"*FSList.fontList:	-*-lucidatypewriter-*-*-*-*-12-*-*-*-*-*-iso8859-1",
"*FSEditor.fontList:	-*-lucidatypewriter-*-*-*-*-12-*-*-*-*-*-iso8859-1",
"*FileName.fontList:	-*-helvetica-bold-o-*-*-14-*-*-*-*-*-iso8859-1",
"*iconFont:		-*-helvetica-*-*-*-*-10-*-*-*-*-*-iso8859-1",
"*lBoxDirectoryTitleSrc.fontList: -*-helvetica-bold-o-*-*-18-*-*-*-*-*-iso8859-1",
"*lBoxDirectoryTitleDst.fontList: -*-helvetica-bold-o-*-*-18-*-*-*-*-*-iso8859-1",
"*lBoxLicenseTitle.fontList:	-*-helvetica-bold-o-*-*-18-*-*-*-*-*-iso8859-1",
"*lBoxLicense.fontList:		-*-lucidatypewriter-medium-*-*-*-12-*-*-*-*-*-*-*",
"*lBoxSelectTitle.fontList:	-*-helvetica-bold-o-*-*-18-*-*-*-*-*-iso8859-1",
"*lBoxInstallTitle.fontList:	-*-helvetica-bold-o-*-*-18-*-*-*-*-*-iso8859-1",
"*lWaiting.fontList:	-*-helvetica-bold-o-*-*-18-*-*-*-*-*-iso8859-1",
"*lBDSrc.fontList:	-*-helvetica-bold-o-*-*-14-*-*-*-*-*-iso8859-1",
"*lBDDst.fontList:	-*-helvetica-bold-o-*-*-14-*-*-*-*-*-iso8859-1",
"*lBDSrcD.fontList:	-*-lucidatypewriter-medium-*-*-*-12-*-*-*-*-*-iso8859-1",
"*lBDDstD.fontList:	-*-lucidatypewriter-medium-*-*-*-12-*-*-*-*-*-iso8859-1",
"*lBDIfile.fontList:	-*-helvetica-bold-r-*-*-14-*-*-*-*-*-iso8859-1",
"*lBDIpackage.fontList:	-*-helvetica-bold-r-*-*-14-*-*-*-*-*-iso8859-1",
"*lBDItotal.fontList:	-*-helvetica-bold-r-*-*-14-*-*-*-*-*-iso8859-1",
"*lBDIinfo.fontList:	-*-helvetica-bold-o-*-*-14-*-*-*-*-*-iso8859-1",
"*installNormal:		-*-helvetica-medium-r-*-*-14-*-*-*-*-*-iso8859-1",
"*installItalic:		-*-helvetica-medium-*-*-*-14-*-*-*-*-*-iso8859-1",
"*lFSCreate.fontList:	-*-helvetica-medium-*-*-*-10-*-*-*-*-*-iso8859-1",
"*lFSInfo.fontList:	-*-helvetica-medium-o-*-*-14-*-*-*-*-*-iso8859-1",
"*lBKInfo.fontList:	-*-helvetica-medium-o-*-*-14-*-*-*-*-*-iso8859-1",
"*gBoxKeyAsk*XmLabel.fontList:	-*-helvetica-bold-o-*-*-14-*-*-*-*-*-iso8859-1",
"*gBoxKeyAsk*XmTextField.fontList: -*-lucidatypewriter-medium-*-*-*-12-*-*-*-*-*-*-*",
"*lBKGLabel1.fontList:	-*-helvetica-medium-*-*-*-10-*-*-*-*-*-iso8859-1",
"*lBKGLabel2.fontList:	-*-helvetica-medium-*-*-*-10-*-*-*-*-*-iso8859-1",
"*lBKGLabel3.fontList:	-*-helvetica-medium-*-*-*-10-*-*-*-*-*-iso8859-1",
"*lBKGLabel4.fontList:	-*-helvetica-medium-*-*-*-10-*-*-*-*-*-iso8859-1",
"*msgalert_bboard*XmLabelGadget.fontList: -*-helvetica-bold-o-*-*-18-*-*-*-*-*-iso8859-1",
"*lBKGLabel1.labelString:	Xclamation   [OK]",
"*lBKGLabel2.labelString:	XQuad   [OK]",
"*lBKGLabel3.labelString:	XAllWrite   [OK] ",
"*lBKGLabel4.labelString:	XMayday   [OK]",
"*highlightThickness:			1",
"*XmLabel.highlightThickness:		0",
"*lBDDstSpace.highlightThickness:	0",
"*lBKInfo.highlightThickness:		0",
"*lBKGLabel1.highlightThickness:		0",
"*lBKGLabel2.highlightThickness:		0",
"*lBKGLabel3.highlightThickness:		0",
"*lBKGLabel4.highlightThickness:		0",
"*indicatorSize:				13",
"*XmRadioBox.marginHeight:		0",
"*XmRadioBox.spacing:			0",
"*XmToggleButton.enableToggleVisual:	True",
"*XmToggleButtonGadget.enableToggleVisual: True",
"*XmToggleButton.indicatorType:		XmONE_OF_MANY",
"*XmToggleButtonGadget.indicatorType:	XmONE_OF_MANY",
"*shadowThickness:				1",
"*XmFrame.shadowThickness:			2",
"*XmLabel.shadowThickness:			0",
"*XmSeparatorGadget.shadowThickness:		8",
"*XmSeparator.shadowThickness:			8",
"*XmRowColumn.shadowThickness:			1",
"*XmCascadeButtonGadget.shadowThickness:		1",
"*XmScrollBar.shadowThickness:			1",
"*XmBulletinBoard.shadowThickness:		0",
"*XmForm.shadowThickness:			0",
"*tbBSSelect.shadowThickness:			0",
"*tbBSSelect.highlightThickness:			0",
"*tbBSIconPack.highlightThickness:		0",
"*gBoxSelect2*XmPushButton.highlightThickness:	0",
"*gBoxSelect2*XmPushButton.shadowThickness:	0",
"*XmLabel.marginLeft:				5",
"*XmLabel.marginRight:				5",
"*XmLabel.recomputeSize:				False",
"*XmFrame.XmLabel.marginLeft:			1",
"*XmFrame.XmLabel.marginRight:			1",
"*fBDSrc.marginHeight:				20",
"*fBDDst.marginHeight:				20",
"*lFSCreate.marginLeft:				5",
"*lFSCreate.marginRight:				5",
"*XmCascadeButtonGadget.marginWidth:		8",
"*XmCascadeButtonGadget.marginHeight:		2",
"*XmPushButtonGadget.marginWidth:		8",
"*XmPushButtonGadget.marginHeight:		2",
"*XmToggleButtonGadget.marginWidth:		5",
"*XmToggleButtonGadget.marginHeight:		1",
"*XmLabel.marginWidth:				0",
"*XmLabel.marginHeight:				0",
"*tbBSSelect.marginRight:			10",
"*tbBSSelect.marginHeight:			0",
"*gBoxLanguage.marginWidth:			20",
"*gBoxLicense.marginWidth:			20",
"*gBoxSelect2*XmToggleButton.recomputeSize:	False",
"*gBoxSelect2*XmToggleButton.marginHeight:	0",
"*gBoxSelect2*XmToggleButton.marginRight:	0",
"*gBoxSelect2*XmToggleButton.marginLeft:		0",
"*gBoxSelect2*XmToggleButton.indicatorOn:	False",
"*gBoxSelect2*XmToggleButton.spacing:		0",
"*gBoxSelect2*XmToggleButton.width:		25",
"*gBoxSelect2*XmLabel.recomputeSize:		True",
"*gBoxSelect2*XmLabel.marginHeight:		0",
"*gBoxSelect2*XmLabel.marginRight:		6",
"*gBoxSelect2*XmLabel.marginLeft:		6",
"*gBoxKeyAsk.marginWidth:			0",
"*gBoxKeyAsk.marginHeight:			0",
"*gBoxKeyIcons.marginWidth:			0",
"*gBoxKeyIcons.marginHeight:			0",
"*lBoxLicense.recomputeSize:			True",
"*XmFrame.marginHeight:				0",
"*XmFrame.marginWidth:				0",
"*item_menu.XmLabel.marginLeft:			6",
"*item_menu.XmLabel.marginRight:			12",
"*lBDSrcD.marginHeight:	10",
"*lBDDstD.marginHeight:	10",
"*lBDSrcD.editable:	False",
"*lBDDstD.editable:	False",
"*lBDSrcD.traversalOn:	False",
"*lBDDstD.traversalOn:	False",
"*lBDSrcD.cursorPositionVisible: False",
"*lBDDstD.cursorPositionVisible: False",
"*XmDrawingArea.traversalOn:	False",
"*XmPushButtonGadget.shadowType:		XmSHADOW_IN",
"*lBDDstD.alignment:			ALIGNMENT_BEGINNING",
"*lBDDst.alignment:			ALIGNMENT_END",
"*lBDSrc.alignment:			ALIGNMENT_END",
"*lBDIfilep.alignment:			ALIGNMENT_END",
"*lBDIpackagep.alignment:		ALIGNMENT_END",
"*lBDItotalp.alignment:			ALIGNMENT_END",
"*lBDIfileName.alignment:		ALIGNMENT_BEGINNING",
"*lBDIpackageName.alignment:		ALIGNMENT_BEGINNING",
"*lBoxLicense.alignment:			ALIGNMENT_BEGINNING",
"*gBoxKeyAsk*alignment:			ALIGNMENT_END",
"*background:				gray65",
"*XmList.background:			gray60",
"*borderWidth: 0",
"*stBoxLicense*background: 		#9E6161",
"*stBoxLicense*borderWidth: 		0",
"*lBoxLicense.marginLeft:		13",
"*lBoxLicense.marginRight:		8",
"*stBoxLicense.highlightThickness: 	2",
"*lBoxLicense.highlightThickness: 	0",
"*stBoxLicense.shadowThickness: 		0",
"*stBoxLicense.spacing: 			0",
"*stBoxLicense*traversalOn: True",
"*stBoxLicense*scrollBarDisplayPolicy: AS_NEEDED",
"*stBoxLicense*scrolledWindowMarginWidth:	0",
"*stBoxLicense*scrolledWindowMarginHeight:	0",
"*BKDrawingGIF.background: white",
"*ClipboardPrivate.PrivateClipArea.background: gray60",
"*PrivateClipArea*XmLabel.background:	gray60",
"*XmToggleButtonGadget.selectColor:   	yellow",
"*action_area.XmPushButton.background:	#B1B0B8",
"*BDIconDst.background:			#B1B0B8",
"*BDIconSrc.background:			#B1B0B8",
"*lFSCreate.background:			#B1B0B8",
"*gBoxSelect2*XmPushButton.armColor:	gray65",
"*lBIInfo2.background:			gray65",
"*XmTextField.background:		#BCB5BA",
"*XmText.background:			#BCB5BA",
"*borderColor:				gray65",
"*Application*borderColor:		black",
"*XmFrame.foreground:			gray30",
"*BKIconTitle.background:		white",
"*lBoxDirectoryTitleSrc.foreground:	white",
"*lBoxDirectoryTitleDst.foreground:	white",
"*lBoxLicense.foreground:		white",
"*lBoxLicenseTitle.foreground:		white",
"*lBoxSelectTitle.foreground:		white",
"*lBoxInstallTitle.foreground:		white",
"*lBKInfo.foreground:			white",
"*gFile*background:			gray60",
"*gPackage*background:			gray50",
"*gTotal*background:			gray40",
"*lBDDstSpace.foreground:		white",
"*lBDSrcD.background:		gray60",
"*lBDDstD.background:		gray60",
"*lBKGLabel1.foreground:		white",
"*lBKGLabel2.foreground:		white",
"*lBKGLabel3.foreground:		white",
"*lBKGLabel4.foreground:		white",
"*gFile*XmFrame.shadowType:		SHADOW_IN",
"*gPackage*XmFrame.shadowType:		SHADOW_IN",
"*gTotal*XmFrame.shadowType:		SHADOW_IN",
"*gFile*XmFrame.shadowThickness:		1",
"*gPackage*XmFrame.shadowThickness:	1",
"*gTotal*XmFrame.shadowThickness:	1	",
"*highlightColor:			gray30",
"*XmScrolledWindow*translations:         #override               \\n\
                        <Btn4Down>:     xc_dispatch_event()     \\n\
                        <Btn5Down>:     xc_dispatch_event()     \\n",
"*XmScrolledWindow.XmScrollBar.translations:	#override	\\n\
~Meta ~Alt Ctrl         <Btn4Down>:     PageUpOrLeft(0)         \\n\
                        <Btn4Down>:     IncrementUpOrLeft(0)    \\n\
~Meta ~Alt Ctrl         <Btn5Down>:     PageDownOrRight(0)      \\n\
                        <Btn5Down>:     IncrementDownOrRight(0)	\\n",
"*XmTextField.translations:		#override		\\n\
 ~Meta ~Alt Ctrl<Key>a:		beginning-of-line()		\\n\
 ~Meta ~Alt Ctrl<Key>b:		backward-character()		\\n\
 ~Meta ~Alt Ctrl<Key>d:		delete-next-character()		\\n\
 ~Meta ~Alt Ctrl<Key>e:		end-of-line()			\\n\
 ~Meta ~Alt Ctrl<Key>f:		forward-character()		\\n\
 ~Meta ~Alt Ctrl<Key>g:		process-cancel()		\\n\
 ~Meta ~Alt Ctrl<Key>h:		delete-previous-character()	\\n\
 ~Meta ~Alt Ctrl<Key>k:		delete-to-end-of-line()		\\n\
 ~Meta ~Alt Ctrl<Key>u:		beginning-of-line()		\
				delete-to-end-of-line()		\\n\
 ~Meta ~Alt Ctrl<Key>w:		cut-clipboard()			\\n\
 Meta ~Ctrl<Key>b:		backward-word()			\\n\
  Alt ~Ctrl<Key>b:		backward-word()			\\n\
 Meta ~Ctrl<Key>d:		delete-next-word()		\\n\
  Alt ~Ctrl<Key>d:		delete-next-word()		\\n\
 Meta ~Ctrl<Key>f:		forward-word()			\\n\
  Alt ~Ctrl<Key>f:		forward-word()			\\n\
 Meta ~Ctrl<Key>w:		copy-clipboard()		\\n\
  Alt ~Ctrl<Key>w:		copy-clipboard()		\\n\
 Meta ~Ctrl<Key>osfLeft:	backward-word()			\\n\
  Alt ~Ctrl<Key>osfLeft:	backward-word()			\\n\
 Meta ~Ctrl<Key>osfRight:	forward-word()			\\n\
  Alt ~Ctrl<Key>osfRight:	forward-word()			\\n\
 Meta ~Ctrl<Key>osfBackSpace:	delete-previous-word()		\\n\
  Alt ~Ctrl<Key>osfBackSpace:	delete-previous-word()		\\n\
 Meta ~Ctrl<Key>osfDelete:	delete-next-word()		\\n\
  Alt ~Ctrl<Key>osfDelete:	delete-next-word()		\\n",
"*tfKey.translations:			#override		\\n\
 \"000\":				xc_insert_string(\"0000000000\")	\\n\
 \"00\":				xc_insert_string(\"0\")		\\n\
 \"0\":				xc_insert_string(\"0\")		\\n",
"*bboard.backgroundPixmap:		leather_dark",
"*bboard.action_area.backgroundPixmap:	leather_dark",
"*gBoxLicense.backgroundPixmap:		leather_dark",
"*lBoxLicenseTitle.backgroundPixmap:	leather_dark",
"*gBoxKey.backgroundPixmap:		leather_dark",
"*gBoxDirectory.backgroundPixmap:	leather_dark",
"*lBoxDirectoryTitleSrc.backgroundPixmap: leather_dark",
"*lBoxDirectoryTitleDst.backgroundPixmap: leather_dark",
"*formWaiting.backgroundPixmap:		leather_dark",
"*gBoxSelect.backgroundPixmap:		leather_dark",
"*lBoxSelectTitle.backgroundPixmap:	leather_dark",
"*gBoxInstall.backgroundPixmap:		leather_dark",
"*lBoxInstallTitle.backgroundPixmap:	leather_dark",
"*gBoxLanguage.backgroundPixmap:		leather_dark",
"*gBoxKeyIcons.backgroundPixmap:		leather_dark",
"*gBoxKeyLabels.backgroundPixmap:	leather_dark",
"*gFile*XmDrawingArea.background:	black",
"*gPackage*XmDrawingArea.background:	black",
"*gTotal*XmDrawingArea.background:	black",
