#!/bin/sh
#
# do_rc for Xclamation, XQuad, XAllWrite and XMayday in Utils/
# Create all languages's RC files
#
# Copyright (C) 1994-2000 Axene.
# Authors: Stéphane Boisson, Antoine Buat, Robin Castanier and Emmanuel Paris.
# Email: xcalibur@axene.org
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
# Started on  Mon Dec  8 17:12:44 1997 Emmanuel Paris
# Last update Fri Jan  7 14:30:46 2000 Emmanuel Paris
#

PWD=`pwd`
top=`dirname $PWD/$0`
rc_dir="$top/../RC"
configure_file="$rc_dir/configure"
echonl="$top/echonl.sh"

dst_file=
rc_seq_file=
rc_lang=
dst_lang=

#--- Init global functions
progname=`basename $0`
SkipLine() { echo " "; }
Fatal() { echo "${progname} Error: ${1}" 1>&2 ; exit 1; }

test -r $configure_file || Fatal "The \`configure' file is missing!"

count=0
exec 5<$configure_file
while read conf <&5 ; do
 count=`expr $count + 1`
 if [ "v$conf" != "v" ]; then
 line=`echo $conf | grep "^[ \t]*\#"`
 if [ -z  "$line" ]; then
   eval "$conf" 2> /dev/null || Fatal "Syntax Error Line $count !"
  fi
 fi
done

if [ "v$dst_file" = "v" ]; then Fatal "\$dst_file empty or missing !"; fi
if [ "v$rc_seq_file" = "v" ]; then Fatal "\$rc_seq_file empty or missing !"; fi
if [ "v$rc_lang" = "v" ]; then Fatal "\$rc_seq_file empty or missing !"; fi
if [ "v$rc_seq_file" = "v" ]; then Fatal "\$rc_seq_file empty or missing !"; fi

clean=`echo $1 | grep "clea[rn]"`
if [ "v$clean" != "v" ]; then
 $echonl "Cleaning RC files: "
 for lang in $dst_lang; do
  if [ -r $rc_dir/$dst_file.$lang ]; then 
   $echonl "."
   rm -f $rc_dir/$dst_file.$lang
  fi
 done
  if [ -r $rc_dir/uptodate ]; then 
   $echonl "."
   rm -f $rc_dir/uptodate
  fi
 echo "done."
 exit 0
fi

$echonl "Making RC files:"

error=
count=0

for lang in $rc_lang; do
 count2=0
 dest=
 for lang2 in $dst_lang; do
  if [ $count = $count2 ]; then
   break
  fi
  count2=`expr $count2 + 1`
 done
 if [ "v$lang2" = "v" ]; then 
  SkipLine 
  Fatal "not enough item in \$dst_lang !"
 fi

 if [ $count = 0 ]; then 
  $echonl " "$lang2
 else
  tst_end=`echo "$rc_lang" | grep $lang\$`
  if [ "v$tst_end" != "v" ]; then
   $echonl " and "$lang2
  else
   $echonl ", "$lang2
  fi
 fi 
 count=`expr $count + 1`

 echo "\CONFIG{" > $rc_dir/$dst_file.$lang2
 for rc_file in $rc_seq_file; do
  src_file=`eval echo $rc_file`
  src_file=`eval echo $src_file`
  if [ -r $rc_dir/$src_file ]; then 
   cat $rc_dir/$src_file >> $rc_dir/$dst_file.$lang2
  else
   error=$error" "$src_file
  fi
 done
 echo "}" >> $rc_dir/$dst_file.$lang2
done        

echo "."

touch $rc_dir/uptodate

if [ "v$error" != "v" ]; then Fatal "Files $error is/are missing."; fi

