#!/bin/tcsh -fb
#
# do_cleantar for Xclamation, XQuad, XAllWrite, XMayday, XInstall and 
# 	AxeneOffice in Utils/
# Clean recursively all directories of tar and compressed files.
#
# Copyright (C) 1994-2000 Axene.
# Authors: Stéphane Boisson, Antoine Buat, Robin Castanier and Emmanuel Paris.
# Email: xcalibur@axene.org
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
# Started on  Sometime during     1998 One of the authors
# Last update Sat Jun  5 12:49:22 1999 Emmanuel Paris
#

set cmd = $0
if ($# == 1) then
  set gato = ${1}
else
  set gato = `pwd`
endif

cd ${gato} >& /dev/null
echo Cleaning: `pwd`

rm -i *.tgz *.tar *.gz *.Z *.z >& /dev/null
foreach i (*)
 if ( -d ${i} ) then
   if( ${i} != 'RCS' ) then
     ${cmd} ${i}
   endif
 endif
end
