"*title:					Axene XInstall",
"*action_area.Yes.labelString:		Oui",
"*action_area.No.labelString:		Non",
"*action_area.Apply.labelString:		Appliquer",
"*action_area.Ok.labelString:		Ok",
"*action_area.Open.labelString:		Ouvrir...",
"*action_area.Retry.labelString:		Recommencer",
"*action_area.Stop.labelString:		Arrêter",
"*action_area.Reset.labelString:		Réinitialiser",
"*action_area.Cancel.labelString:	Annuler",
"*action_area.Close.labelString:		Fermer",
"*action_area.Help.labelString:		Aide",
"*action_area.Save.labelString:		Sauver",
"*action_area.Continue.labelString:	Continuer",
"*action_area.Quit.labelString:		Quitter",
"*action_area.Save as.labelString:	Sauver sous...",
"*action_area.Back.labelString:		<<< Précédent",
"*action_area.Next.labelString:		Suivant >>>",
"*action_area.Install.labelString:	Installer",
"*action_area.DontAgree.labelString:	Je n'accepte pas",
"*action_area.Agree.labelString:		J'accepte >>>",
"*sigErrorSEGVMsg:	Violation de privilèges (Segmentation fault)",
"*sigErrorPIPEMsg:	Connexion interrompue (Broken pipe)",
"*sigErrorBUSMsg:	Erreur de bus (Bus error)",
"*sigErrorFPEMsg:	Erreur de calcul (Floating exception)",
"*sigErrorIOTMsg:	Erreur interne (IOT trap)",
"*sigErrorEMTMsg:	Déroutement Erreur mémoire (EMT trap)",
"*sigErrorXCPUMsg:	Dépassement de temps CPU (Cputime limit exceeded)",
"*sigErrorXFSZMsg:	Dépassement de taille fichier (Filesize limit exceeded)",
"*sigErrorILLMsg:	Instruction illicite (Illegal instruction)",
"*sigErrorINTMsg:	Axene XInstall a été interrompu (Interrupt)",
"*sigErrorQuitingMsg:	Quitter Axene XInstall maintenant",
"*sigErrorSorryMsg:	Impossible de continuer l'exécution",
"*lCaughtSignal.labelString:		Une erreur est survenue :",
"*lCaughtIOerror.labelString:		Erreur fatale du serveur X",
"*lCannotContinue.labelString:		Impossible de continuer",
"*lBoxLicenseTitle.labelString:		L'installation et l'utilisation des\
 logiciels Axene\\nnécessitent l'acceptation des termes et conditions suivants :",
"*lBKInfo.labelString:		Pour enregistrer les logiciels Axene,\
 vous devez  posseder une clef d'enregistrement.\\n Entrez la clef\
 '000-0000000000' pour installer sans enregistrement.",
"*lBKInfoMsg:	INSTALLATION LIVE.\\n\
Entrez votre clef ici..",
"*lBKFName.labelString:		Prénom, Nom",
"*lBKCompany.labelString:	Société",
"*lBKKey.labelString:		Clef",
"*keynotvalidMsg:		Cette clef n'est pas valide.",
"*lBoxDirectoryTitleSrc.labelString: Les archives seront installées depuis\
 le répertoire suivant.\\nPour installer depuis un autre répertoire, clickez\
 sur l'icone.",
"*lBoxDirectoryTitleDst.labelString: Les logiciels vont être installés dans\
 le répertoire suivant.\\nPour installer dans un autre répertoire, clickez\
 sur l'icone.",
"*lBDSrc.labelString:		Source :",
"*lBDDst.labelString:		Destination :",
"*lFSCreate.labelString:		Ajouter répertoire",
"*lWaiting.labelString:		Recherche des archives...",
"*freeSpaceMsg:			Espace disponible : %ld Ko",
"*createdirMsg:			Le répertoire %s \\nn'existe pas. Voulez vous le créer ?",
"*cannotCreateDirMsg:		Impossible de créer le répertoire %s",
"*dirNotWritableMsg:		Vous n'avez pas accès en écriture dans\\nle répertoire %s.",
"*lBoxSelectTitle.labelString:	Sélection des archives à installer",
"*browseDirectorySrcMsg:		Sélection du répertoire source",
"*browseDirectoryDstMsg:		Sélection du répertoire de destination",
"*usedSpaceMsg:			Espace nécessaire : %ld Ko",
"*noPackageFoundMsg:		Aucune archive trouvée",
"*onePackageFoundMsg:		1 archive trouvée",
"*manyPackageFoundMsg:		%d archives trouvées",
"*noPackageSelectedMsg:		Aucune archive sélectionnée",
"*onePackageSelectedMsg:		1 archive sélectionnée",
"*manyPackageSelectedMsg:	%d archives sélectionnées",
"*sizeMsg:			Taille",
"*demoMsg:			Démonstration",
"*manualMsg:			Manuel",
"*librariesMsg:			Librairies Communes",
"*bytesMsg:			Octets",
"*kiloBytesMsg:			Ko",
"*megaBytesMsg:			Mo",
"*notEnoughSpaceMsg:		Il n'y a pas assez d'espace disque pour installer\\ntoutes les archives choisies. Il manque %d Ko.",
"*lBoxInstallTitle.labelString:	Installation en cours...",
"*lBDIfilep.labelString:		0%",
"*lBDIpackagep.labelString:	0%",
"*lBDItotalp.labelString:	0%",
"*lBDIfile.labelString:		Fichier",
"*lBDIpackage.labelString:	Archive",
"*lBDItotal.labelString:		Total",
"*lBDIinfo.labelString:		",
"*lBDIspace.labelString:		Espace disponible :",
"*lBDIspacep.labelString:	(--%)",
"*lBDIspacea.labelString:	??? Ko",
"*freeSpace2Msg:			%ld Ko",
"*installCompleteMsg:		Installation terminée !",
"*installQuitMsg:		Quitter",
"*installEndMessageMsg:		L'installation des archives sélectionnées\\n\
est maintenant terminée.",
"*notavailableMsg:		non disponible",
"*quitMessageMsg:		L'installation n'est pas terminée.\\n\
Si vous quittez maintenant, les logiciels ne seront pas installés.\\n\
Vous pouvez choisir Continuer pour reprendre l'installation.",
